#!/bin/bash

#Script for copy files to externall hdd with 
#respect of already copied file on target system
#option F is on can spec .rsync-filter in from dir

rsync=$(which rsync)

##default
#rsync_args="-avr --progress"
rsync_args="-avr --progress"

hdd="${1%/}"

if [ ! -d "$hdd" ]
then
	echo "No such directory '$hdd'"
	exit 1
fi


rsync_args2=$2

#origin of files
from="from/"

#target of files
target="server.pyt.lan:share/videos/series/"


ignore=$hdd/ignore.lst

ignoretmp="/tmp/ignore.lst"


#Get ignore list
echo "; Ignore for '$target' at $(date)" > $ignoretmp
rsync -r "$target" --list-only | \
	awk '
		function basename(file) {
   			sub(".*/", "", file)
    		return file
  		}

		/^-/ {print basename(substr($0, index($0, $5)))}' \
	>> $ignoretmp

if [ $? -ne '0' ] 
then
	echo "Warning! No ignore file created $?"
else
	mv "$ignoretmp" "$ignore"
fi

dirignore="-F --exclude '.rsync-filter'"

param=""

if [ -f "$ignore" ]
then
	param="--exclude-from \"$ignore\""
fi

cmd="\"$rsync\" $rsync_args $rsync_args2 $dirignore \"$from\" \"$hdd\" $param"

echo $cmd

eval $cmd



