#!/bin/bash

target="./target"

hdd="${1%/}"

if [ ! -d "$hdd" ]
then
	echo "No such directory '$hdd'"
	exit 1
fi

rsync=$(which rsync)

rsync_args="-avrh --progress -F --exclude '.rsync-filter' --exclude 'ignore.lst'"

rsync_args2=$2

cmd="$rsync $rsync_args $rsync_args2 \"$hdd\" \"$target\""

echo $cmd

eval $cmd