#!/bin/bash

from="no file"

rsync=$(which rsync)

rsync_args="-avrh --progress"

rsync_args2=${@:2}

userConf="config"

if [ "${2:-n}" == "-c" ]
then
	userConf=$3
	rsync_args2=${@:4}
fi

if [ "$1" == "-h" ]
then
	echo Script for copy files FROM externall hdd with 
	echo respect of already copied file on target system
	echo use option -F, you can spec .rsync-filter in from dir
	echo
	echo "Usage $(basename $0) <path-to-hdd> [-c <config>][<more rsync flags>]"
	exit 0
fi

#Check configs

conf_loaded=false

if [ -f "/etc/sync-to-hdd.conf" ]
then
	source "/etc/sync-to-hdd.conf"
	echo Global conf loaded
	conf_loaded=true
fi

if [ -f "$HOME/.sync-to-hdd.rc" ]
then
	source "$HOME/.sync-to-hdd.rc"
	echo User conf loaded
	conf_loaded=true
fi

if [ -f "$userConf" ]
then
	source "$userConf"
	echo "Immediate '$userConf' conf loadded"
	conf_loaded=true
fi

if [ "$conf_loaded" == "false" ]
then
	echo "No config found!"
	exit 1
fi

hdd="${1%/}"

if [ ! -d "$hdd" ]
then
	echo "No such directory '$hdd'"
	exit 1
fi

exclude="--exclude '.rsync-filter' --exclude 'ignore.lst'"

cmd="$rsync $rsync_args $exclude $rsync_args2 \"$hdd\" \"$from\""

echo $cmd

eval $cmd